---
title: "Community and Collaboration: Writing a Book in the Open (Introduction)"
author: "Ryan Estrellado"
date: "5/17/2020"
output: html_document
---

In 2017, Emily Bovee, Jesse Mostipak, Joshua Rosenberg, Isabella Velásquez, and I started work on our book, Data Science in Education Using R (DSIEUR). We had two goals for DSIEUR. First, we aimed to write a practical reference for data scientists in education that helps them learn and apply R skills in their jobs. Second, we wanted to share the process with the R community by writing the book in the open on GitHub. After working together for almost three years, my co-authors and I submitted the manuscript for DSIEUR to Routledge and are now gearing up to begin editing the print version. The print version will be out from Routledge in late 2020, but you can read the online version of DSIEUR now at [https://datascienceineducation.com/](https://datascienceineducation.com/). 

With the writing done, we’re reflecting on lessons we’ve learned from writing DSIEUR. In the coming weeks, we’ll share these reflections on R Views as a series of blog posts. These posts are about the people and tools in the R community that inspired us to do a book like DSIEUR. Think of these as our personal notes, typed up to help us organize our thoughts about what made this project possible. We’ll share in four parts:

### Part 1: Teaching R Using Everyday Examples in Education

Learning R on the job presents many challenges, but one in particular sticks out. Once you start coding, "it's not obvious how to apply that code in everyday tasks at the office. We wrote DSIEUR to answer the question, “How would it feel to have a book that taught programming concepts, provided reproducible code, and used scenarios that data scientists in education recognize?” In this first post, we’ll explore how we put these elements together and what we learned in the process. 

### Part 2: How the R Community Inspired Us to Write About Data Science in Education

It wasn’t long before our team encountered our first writing challenge: do we describe our audience as “data scientists in education” or “education data scientists?”. The debate was a symbol for a larger dilemma–what common language do you use when projects like ours aren’t yet common? It helped that the community we were writing for inspired us to explore the topic. The things we love the most about the R community–welcoming folks from different backgrounds, a collective love of side projects, and a willingness to work in the open–made it safe for us to try new things and learn. We listened to stories from data scientists in education, spent a lot of time reading the Twitter #rstats hashtag, and invited community members to join the conversation. In this post, we’ll explore how community participation empowered our writing process. 
	
### Part 3: Writing In the Open

This post is about coordinating people and tools to write an open book, a challenging proposition for five writers who had only just met on Twitter. For instance, how would five people in different time zones write instructional materials and code together? And if coordinating five authors wasn’t hard enough, how would they invite the rest of the community to join the mission? Fortunately, people and programming tools encouraged us to believe that this project was possible. R, RStudio, {bookdown}, and Git had already solved publishing and collaboration problems for many. Except for some initial coding gaffes you’d expect from a team finding their feet and the occasional [burned down fork](https://happygitwithr.com/burn.html), these tools freed us to focus on the larger task at hand: finding a common language for data science in education. We’ll close this post by discussing how books, authored through an open-source approach, can serve as an innovative platform for sharing knowledge with a wider audience. 

### Conclusion: One Writer, Five Authors. 

How do you get five points of view to sound like a single voice? You’ll need a flexible sense of clarity, which I think is what Jesse meant when she said in a recent team call, “I have strong opinions, loosely held.” And it helps to have some basic rules as guardrails to flank your team as you march towards your writing deadlines. In this last post, we’ll share the workflows and processes we leaned on to discover what we wanted this book to be. We’ll also share our go-to tactics to keep the work going for the long haul, like managing meeting agendas, creating flexible norms for participation, and playing to individual strengths. 

We’ll be back with that first post in about two weeks. Until then, do share with us about the people and tools that inspire you to work on collaborative projects. You can reach us on Twitter: Emily [@ebovee09](https://twitter.com/ebovee09), Jesse [@kierisi](https://twitter.com/kierisi), Joshua [@jrosenberg6432](https://twitter.com/jrosenberg6432), Isabella [@ivelasq3](https://twitter.com/ivelasq3), and me [@RyanEs](https://twitter.com/RyanEs). 
  
See you in two weeks! 

Ryan, with help from Emily, Jesse, Joshua, and Isabella
